### ISSUE TITLE
The compile fails with the lastest rust.

### ISSUE THREAD

**Issue by Dretch** [grahame/rust-csv#2]
There are 24 errors, mostly of the `illegal borrow unless pure` variety.

**Comment by grahame** [comment]
Yeah, I noticed that. I've got no real idea what those errors mean, and someone just asked on the mailing list, so I'll wait until someone replies there. Patches welcome though :-)

**Comment by Dretch** [comment]
I don't care about this any more, and I don't think anyone else does either!
